### PR TITLE
feat: add support for managed HSM

### LINKED ISSUE #125: Support for Azure Keyvault Managed HSM
ref: https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**Reason for Change**:

- Adds support for managed HSM (`--managed-hsm=true`
- Refactors tests to separate out error and non-error scenarios (xref: https://github.com/golang/go/wiki/TestComments#table-driven-tests-vs-multiple-test-functions)

**Issue Fixed**:

fixes #125 

**Notes for Reviewers**:

### CODE REVIEW

**Comment by aramase** [comment]
- Validated this PR by setting up Key Vault Managed HSM in my dev tenant by following the docs: https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/quick-create-cli
- Tried setting up a managed hsm instance for CI, but the CI tenant is locked down and doesn't allow setting up the instance
- Simulated a failure to check the calls are being sent to managed hms instance when `--managed-hsm=true`: https://dev.azure.com/azure/9b07c6fd-a44b-431f-9baa-683da7f8a10f/_apis/build/builds/39523/logs/20

**Comment by aramase** [comment]
@bingosummer Any chance you can validate with a custom image (`aramase/keyvault:managed-hsm00-linux-amd64`)?

**Review by bingosummer — APPROVED** [review]
Validated with the custom image. It works well.

**Comment by aramase** [comment]
> Validated with the custom image. It works well.

Thanks for validating, @bingosummer!

**Review by nilekhc — APPROVED** [review]

**Pull request merged**
